#!/bin/bash
#Silahkan di recode :)
#Jangan Lupa Subscribe MaulanaRyM

#Variables
b="\033[1m"
u="\033[4m"
bl="\033[30m"
r="\033[31m"
g="\033[32m"
bu="\033[34m"
m="\033[35m"
c="\033[36m"
w="\033[37m"
endc="\033[0m"
enda="\033[0m"
blue="\033[1;34m"
cyan="\033[1;36m"
red="\033[1;31m"

figlet Black | lolcat
figlet Root | lolcat
echo "YOUTUBE : Ekid Root" | lolcat
echo " ADMIN : EBECK KANSAS" | lolcat

###################################################
# CTRL + C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "
echo $cyan"[#]> Thanks"
sleep 1
echo ""
echo $white"[#]> see you gayn :)"
sleep 1
exit
}

lagi=1
while [ $lagi -lt 6 ];
do
echo ""
echo $b "1.  HACK.FACEBOOK${enda}";
echo $r "2.  LOCKED.PROFILE${endc}";
echo $g "3.  PULSA.GRATIS${endc}";
echo $c "4   Lazymux${endc}";
echo $r "5.  Tools-X${endc}";
echo $r "6. Exit${endc}";
echo ""
echo "YOUTUBE : Ekid Root" |lolcat
read -p "ADMIN : EBECK KANSAS" pil;

# HACK.FACEBOOK

case $pil in
1) apt update && apt upgrade
apt install python2
apt install python
pip2 install mechanize
pip2 install requests
apt install git
git clone https://github.com/ebeckhackfb.py
cd ebeckhackfb.py
ls
python2 ebeckhackfb.py


;;

# LOCKED.PROFILE

2) clear
read -p "MASUKAN NO HP LU BOS: " nama
echo "NOMOR INI DISIMPAN" $nama
echo "LOADING..." | lolcat -a -d 100
read -p "MASUKAN TOKEN: " nama
echo "MAAF TOKEN SALAH: " $nama


;;

#PULSA.GRATIS

3) echo "COPY TEMPEL DI WEB:"
echo "https://tembakpulsagratis.com"
echo "....." | lolcat -a -d 100
;;

#Lazymux

4) git clone https://github.com/Gameye98/Lazymux
echo "${y} Installer Lazymux..."
echo "${y} cd Lazymux"
echo "${y} python lazymux.py"
cd /data/data/com.termux/files/home/Lazymux/
python2 /data/data/com.termux/files/home/Lazymux/ lazymux.py

;;

#Tools-X

5) git clone https://github.com/Rajkumrdusad/Tool-X
echo "${y} Installer Tool-X..."
echo "${y} cd Tool-X"
echo "${y} sh install.aex"
cd /data/data/com.termux/files/home/Tool-X
bash /data/data/com.termux/files/home/Tool-X/sh install.aex

;;


6) echo "created by : EBECK KANSAS" | lolcat
exit
;;

*) echo "sorry, pilihan yang kamu cari tidak tersedia"
esac
done
done
